/**
 * Template sample projects — every template ships fully playable: library
 * images, audio clips, transitions, text layers, animations and grade.
 * Generated by scripts/gen_library_samples.py → public/library/samples.json.
 */
import type { ClipAnimation, GradePreset, TransitionKind, TransitionSpec } from "@voyajes/core";
import samplesJson from "../../public/library/samples.json";
import { libraryAssetUrl } from "./library";

export type SampleClip = {
  media: string;
  durationSec: number;
  animation?: ClipAnimation;
  transitionOut?: TransitionKind | null;
  transitionSpec?: TransitionSpec;
};
export type SampleAudio = {
  ref: string;
  at: number;
  durationSec: number;
  volume?: number;
  fadeInSec?: number;
  fadeOutSec?: number;
  loop?: boolean;
  label?: string | null;
};
export type SampleText = {
  role: "title" | "subtitle" | "caption";
  value: string;
  at: number;
  end: number;
  position: "top" | "center" | "bottom" | "lower-third";
  animation?: ClipAnimation;
};
export type TemplateSample = {
  mood: string;
  grade: GradePreset;
  clips: SampleClip[];
  audio: SampleAudio[];
  text: SampleText[];
  invitation?: { hostName?: string; eventName?: string; eventWhen?: string; eventWhere?: string };
  durationSec: number;
  preview: string[];
};

const data = samplesJson as unknown as { samples: Record<string, TemplateSample> };

export function getTemplateSample(templateId: string | undefined): TemplateSample | undefined {
  if (!templateId) return undefined;
  return data.samples[templateId];
}

export function samplePreviewUrls(templateId: string): string[] {
  return (getTemplateSample(templateId)?.preview ?? []).map((p) => libraryAssetUrl(p));
}

/** Fill {eventName}-style tokens from invitation values. */
export function fillTokens(value: string, vars: Record<string, string | undefined>): string {
  return value.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? "");
}
